### ISSUE TITLE
Should @tonymorris / dibblego be unbanned?

### ISSUE THREAD

**Issue by SomeoneWeird** [polyhack/helloworld#19]
So, this is the issue I spoke about in #18. If you want, you can comment ban/unban.
Feel free to express other opinions about it here, too.

The poll will end at midnight Thursday 2nd April AEDT.

Edit: Also, if people want to vote 'ban' but don't want their decision on public record, message me on IRC and we can try work something out.

**Comment by mipearson** [comment]
-1/+1 is potentially confusing. I say 'unban'.

**Comment by sporto** [comment]
unban

**Comment by kvanberendonck** [comment]
unban

**Comment by lukebakker000** [comment]
unban

**Comment by SomeoneWeird** [comment]
changed OP to ban/unban.

**Comment by DamonOehlman** [comment]
unban

**Comment by zachgoldstein** [comment]
unban

**Comment by mwotton** [comment]
unban

**Comment by davidmason** [comment]
I will refrain from voting for now. I do not have enough information to be anything but agnostic on the issue.

Everyone has been told that

> [it has been based over weeks rather than days](https://github.com/polyhack/helloworld/issues/14#issue-64603802)

and it seems like the following accusations are the basis for the ban:

 - [he has often come into channel wanting to begin a fight](https://github.com/polyhack/helloworld/issues/14#issue-64603802)
 - [he has continually derided programmers who use languages that don't match his preference](https://github.com/polyhack/helloworld/issues/14#issue-64603802)
 - [I see dibblego's behaviour as antithetical to [a polyglot community]](https://github.com/polyhack/helloworld/issues/14#issuecomment-86787131)
 - [I find dibblego's behaviour to be extreme and very subjective.](https://github.com/polyhack/helloworld/issues/14#issuecomment-86787131)
 - [he is promoting a contempt for other languages](https://github.com/polyhack/helloworld/issues/14#issuecomment-86787131)
 - [he has insulted people in the channel](https://github.com/polyhack/helloworld/issues/14#issuecomment-86787131)
 - (not stated as an accusation, but seems implied) [derogatory remarks about other people in channel, especially insinuating they are "dumb" or "incompetent" because the don't agree with x, or don't use y](https://github.com/polyhack/helloworld/issues/14#issuecomment-86787283)
 - [Dibblego's behaviour was antisocial and damaging to friendly discussion about a range of programming languages](https://github.com/polyhack/helloworld/issues/14#issuecomment-87329575)
 - [he would (a) flood the channel with his talk and (b) would insult people a lot of the time as he did it](https://github.com/polyhack/helloworld/issues/14#issuecomment-87329575)


but I only saw the interactions immediately preceding the ban, so I can only guess at what else was considered. @radar has helpfully pointed out that [chat logs are recorded](https://github.com/polyhack/helloworld/issues/14#issuecomment-86806029), but should everyone be expected to dig through logs to assess the validity of a ban?

It would not be difficult to grab 2 or 3 representative examples from the past several weeks that illustrate these accusations. I think that is part of due diligence for any non-obvious ban. Ops should be looking at the logs anyway, to make sure they are looking at what was said objectively - we are only human, with malleable memories that are twisted over time by our emotions.


In general I am not in support of a ban that is based on a standard of behaviour that is not being clearly communicated. If I were just going on my experience of Tony's character I would say unban.

**Comment by joshwnj** [comment]
I'm going to echo @davidmason here and say I don't have enough info to cast a vote at this point.  I personally haven't witnessed any of the mentioned antisocial behaviour, but at the same time I respect the opinions of the people who have brought it up. 

Seems like there is some good thought going into how to respond to these situations in future.

**Comment by SomeoneWeird** [comment]
Also, if people want to vote 'ban' but don't want their decision on public record, message me on IRC and we can try work something out.

**Comment by tonymorris** [comment]
I think if any[^1] of the things that @davidmason has mentioned can in any way be justified and I was a proponent of voting (I'm not, but put that aside), I vote for ban.

I want a reasonable and mature forum for critique of tools without unfortunate personal issues. I think we are all capable of that and I would be disappointed to lose that opportunity.

PS: I don't even know it means for someone to have gained exclusive and intimate knowledge of "what another person wants [to begin a fight]." So weird and mysterious.

[^1]: Except for having contempt for programming languages. I think harbouring justifiable contempt for anything believed to be of a poor standard is very important to healthy critique.

**Comment by SomeoneWeird** [comment]
Unbanned.
